### ISSUE TITLE
Architecture Diagrams and Writeups

### ISSUE THREAD

**Issue by pjnorton** [pjnorton/docs#2]
Epic for handling stories related to architecture diagrams
- [ ] #1   Create diagram and writeup for tasks and task-coordinator (agent replacement)
- [ ] #3   Create diagram and writeup for network stack 
- [ ] #4   Create writeup for security changes/requirements 
- [ ] #5   Create diagram and writeup for single node component interaction
- [ ] #6   Create diagram and writeup for node-coordinator-controller 3 layer interaction  
- [ ] #7   Create diagram and writeup for coordinator layer 
- [ ] #8   Create writeup for dhcp architecture 
- [ ] #9   Create writeup and flow diagram for boot process
